services:
  coax:
    image: ghcr.io/themikebachmann/coax:latest
    container_name: coax
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - coax-data:/.coax

volumes:
  coax-data:
